export const Types = {
  RECIPES_GET_DATA_REQUEST: "RECIPES_GET_DATA_REQUEST",
  RECIPES_GET_DATA_LOADING: "RECIPES_GET_DATA_LOADING",
  RECIPES_GET_DATA_SUCCESS: "RECIPES_GET_DATA_SUCCESS",

  RECIPES_GET_DATA_LOAD_MORE_REQUEST: "RECIPES_GET_DATA_LOAD_MORE_REQUEST",
  RECIPES_GET_DATA_LOAD_MORE_LOADING: "RECIPES_GET_DATA_LOAD_MORE_LOADING",
  RECIPES_GET_DATA_LOAD_MORE_SUCCESS: "RECIPES_GET_DATA_LOAD_MORE_SUCCESS",

  RECIPES_SET_CURRENT_SEARCH: "RECIPES_SET_CURRENT_SEARCH",

  RECIPE_GET_DATA_REQUEST: "RECIPE_GET_DATA_REQUEST",
  RECIPE_GET_DATA_SUCCESS: "RECIPE_GET_DATA_SUCCESS",
  RECIPE_GET_DATA_LOADING: "RECIPE_GET_DATA_LOADING",
};
